1516B3PE1_FranckyVercruysse/SpionshopASPNETWebApp/Controllers/TestController.cs
using SpionshopASPNETWebApp.Models.dto;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SpionshopASPNETWebApp.Controllers
{
    public class TestController : Controller
    {
        // GET: Test
        public ActionResult Index()
        {
            return View();
        }

        public async Task<ActionResult> CopyFiles()
        {
            FilesInfoDTO filesInfo = new FilesInfoDTO();
            //filesInfo.FileName = "champagne.gif";
            filesInfo.FileName = "ferrari.gif";
            filesInfo.Artikel_id = 77;

            try
            {
                HttpClient httpClient = new HttpClient();
                string uri = "http://" + Request.Url.Host + ':' + Request.Url.Port + "/CopyAfbeelding/" + filesInfo.FileName + "/" + filesInfo.Artikel_id;
                HttpResponseMessage response = await httpClient.GetAsync(uri);
                response.EnsureSuccessStatusCode();     // Throw on error code.
            }
            catch (Exception ex)
            {
                throw ex;
            }
            return RedirectToAction("Index", "Home");
        }
    }
}

1516B3PE1_FranckyVercruysse/SpionshopASPNETWebApp/Controllers/ToonBestellingController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace SpionshopASPNETWebApp.Controllers
{
    public class ToonBestellingController : Controller
    {
        // GET: ToonBestelling
        public ActionResult Index()
        {
            return View();
        }
    }
}

1516B3PE1_FranckyVercruysse/SpionshopASPNETWebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Spionshop", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, null)</li>*@
                    <li>@Html.ActionLink("Uw bestellingen", "Index", "ToonBestelling", new { area = "" }, null)</li>
                    @*<li>@Html.ActionLink("TestImages", "Index", "Test", new { area = "" }, null)</li>*@
                    @*<li>@Html.ActionLink("CopyFiles", "CopyFiles", "Test", new { area = "" }, null)</li>*@
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>